/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Vox Prismatic
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  SettingsDeleteAccount200,
  SettingsDeleteAccountBody,
  SettingsGetStyle200,
  SettingsProfile200,
  SettingsPutStyle200,
  SettingsPutStyleBody,
  SettingsUpdatePassword200,
  SettingsUpdatePasswordBody,
  SettingsUpdateProfile200,
  SettingsUpdateProfileBody,
  ValidationExceptionResponse
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const settingsProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SettingsProfile200>(
      {url: `/api/settings/profile`, method: 'GET', signal
    },
      );
    }
  

export const getSettingsProfileQueryKey = () => {
    return [`/api/settings/profile`] as const;
    }

    
export const getSettingsProfileQueryOptions = <TData = Awaited<ReturnType<typeof settingsProfile>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsProfile>>> = ({ signal }) => settingsProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsProfileQueryResult = NonNullable<Awaited<ReturnType<typeof settingsProfile>>>
export type SettingsProfileQueryError = AuthenticationExceptionResponse


export function useSettingsProfile<TData = Awaited<ReturnType<typeof settingsProfile>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsProfile>>,
          TError,
          Awaited<ReturnType<typeof settingsProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsProfile<TData = Awaited<ReturnType<typeof settingsProfile>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsProfile>>,
          TError,
          Awaited<ReturnType<typeof settingsProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsProfile<TData = Awaited<ReturnType<typeof settingsProfile>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSettingsProfile<TData = Awaited<ReturnType<typeof settingsProfile>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsProfileQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const settingsUpdateProfile = (
    settingsUpdateProfileBody: SettingsUpdateProfileBody,
 ) => {
      
      
      return customInstance<SettingsUpdateProfile200>(
      {url: `/api/settings/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: settingsUpdateProfileBody
    },
      );
    }
  


export const getSettingsUpdateProfileMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsUpdateProfile>>, TError,{data: SettingsUpdateProfileBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsUpdateProfile>>, TError,{data: SettingsUpdateProfileBody}, TContext> => {

const mutationKey = ['settingsUpdateProfile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsUpdateProfile>>, {data: SettingsUpdateProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  settingsUpdateProfile(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsUpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof settingsUpdateProfile>>>
    export type SettingsUpdateProfileMutationBody = SettingsUpdateProfileBody
    export type SettingsUpdateProfileMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSettingsUpdateProfile = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsUpdateProfile>>, TError,{data: SettingsUpdateProfileBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsUpdateProfile>>,
        TError,
        {data: SettingsUpdateProfileBody},
        TContext
      > => {

      const mutationOptions = getSettingsUpdateProfileMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const settingsUpdatePassword = (
    settingsUpdatePasswordBody: SettingsUpdatePasswordBody,
 ) => {
      
      
      return customInstance<SettingsUpdatePassword200>(
      {url: `/api/settings/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: settingsUpdatePasswordBody
    },
      );
    }
  


export const getSettingsUpdatePasswordMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsUpdatePassword>>, TError,{data: SettingsUpdatePasswordBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsUpdatePassword>>, TError,{data: SettingsUpdatePasswordBody}, TContext> => {

const mutationKey = ['settingsUpdatePassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsUpdatePassword>>, {data: SettingsUpdatePasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  settingsUpdatePassword(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsUpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof settingsUpdatePassword>>>
    export type SettingsUpdatePasswordMutationBody = SettingsUpdatePasswordBody
    export type SettingsUpdatePasswordMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSettingsUpdatePassword = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsUpdatePassword>>, TError,{data: SettingsUpdatePasswordBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsUpdatePassword>>,
        TError,
        {data: SettingsUpdatePasswordBody},
        TContext
      > => {

      const mutationOptions = getSettingsUpdatePasswordMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const settingsGetStyle = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SettingsGetStyle200>(
      {url: `/api/settings/style`, method: 'GET', signal
    },
      );
    }
  

export const getSettingsGetStyleQueryKey = () => {
    return [`/api/settings/style`] as const;
    }

    
export const getSettingsGetStyleQueryOptions = <TData = Awaited<ReturnType<typeof settingsGetStyle>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsGetStyleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsGetStyle>>> = ({ signal }) => settingsGetStyle(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsGetStyleQueryResult = NonNullable<Awaited<ReturnType<typeof settingsGetStyle>>>
export type SettingsGetStyleQueryError = AuthenticationExceptionResponse


export function useSettingsGetStyle<TData = Awaited<ReturnType<typeof settingsGetStyle>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGetStyle>>,
          TError,
          Awaited<ReturnType<typeof settingsGetStyle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsGetStyle<TData = Awaited<ReturnType<typeof settingsGetStyle>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGetStyle>>,
          TError,
          Awaited<ReturnType<typeof settingsGetStyle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsGetStyle<TData = Awaited<ReturnType<typeof settingsGetStyle>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSettingsGetStyle<TData = Awaited<ReturnType<typeof settingsGetStyle>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsGetStyle>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsGetStyleQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const settingsPutStyle = (
    settingsPutStyleBody: SettingsPutStyleBody,
 ) => {
      
      
      return customInstance<SettingsPutStyle200>(
      {url: `/api/settings/style`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: settingsPutStyleBody
    },
      );
    }
  


export const getSettingsPutStyleMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsPutStyle>>, TError,{data: SettingsPutStyleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsPutStyle>>, TError,{data: SettingsPutStyleBody}, TContext> => {

const mutationKey = ['settingsPutStyle'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsPutStyle>>, {data: SettingsPutStyleBody}> = (props) => {
          const {data} = props ?? {};

          return  settingsPutStyle(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsPutStyleMutationResult = NonNullable<Awaited<ReturnType<typeof settingsPutStyle>>>
    export type SettingsPutStyleMutationBody = SettingsPutStyleBody
    export type SettingsPutStyleMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSettingsPutStyle = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsPutStyle>>, TError,{data: SettingsPutStyleBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsPutStyle>>,
        TError,
        {data: SettingsPutStyleBody},
        TContext
      > => {

      const mutationOptions = getSettingsPutStyleMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const settingsDeleteAccount = (
    settingsDeleteAccountBody: SettingsDeleteAccountBody,
 ) => {
      
      
      return customInstance<SettingsDeleteAccount200>(
      {url: `/api/settings/account`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: settingsDeleteAccountBody
    },
      );
    }
  


export const getSettingsDeleteAccountMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsDeleteAccount>>, TError,{data: SettingsDeleteAccountBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsDeleteAccount>>, TError,{data: SettingsDeleteAccountBody}, TContext> => {

const mutationKey = ['settingsDeleteAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsDeleteAccount>>, {data: SettingsDeleteAccountBody}> = (props) => {
          const {data} = props ?? {};

          return  settingsDeleteAccount(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsDeleteAccountMutationResult = NonNullable<Awaited<ReturnType<typeof settingsDeleteAccount>>>
    export type SettingsDeleteAccountMutationBody = SettingsDeleteAccountBody
    export type SettingsDeleteAccountMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSettingsDeleteAccount = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsDeleteAccount>>, TError,{data: SettingsDeleteAccountBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsDeleteAccount>>,
        TError,
        {data: SettingsDeleteAccountBody},
        TContext
      > => {

      const mutationOptions = getSettingsDeleteAccountMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    