/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Laravel
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  SchedulingGetPreferences200,
  SchedulingGetSlots200,
  SchedulingUpdatePreferences200,
  SchedulingUpdatePreferencesBody,
  SchedulingUpdateSlots200,
  SchedulingUpdateSlotsBody,
  ValidationExceptionResponse
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const schedulingGetPreferences = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SchedulingGetPreferences200>(
      {url: `/scheduling/preferences`, method: 'GET', signal
    },
      );
    }
  

export const getSchedulingGetPreferencesQueryKey = () => {
    return [`/scheduling/preferences`] as const;
    }

    
export const getSchedulingGetPreferencesQueryOptions = <TData = Awaited<ReturnType<typeof schedulingGetPreferences>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSchedulingGetPreferencesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof schedulingGetPreferences>>> = ({ signal }) => schedulingGetPreferences(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SchedulingGetPreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof schedulingGetPreferences>>>
export type SchedulingGetPreferencesQueryError = AuthenticationExceptionResponse


export function useSchedulingGetPreferences<TData = Awaited<ReturnType<typeof schedulingGetPreferences>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulingGetPreferences>>,
          TError,
          Awaited<ReturnType<typeof schedulingGetPreferences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSchedulingGetPreferences<TData = Awaited<ReturnType<typeof schedulingGetPreferences>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulingGetPreferences>>,
          TError,
          Awaited<ReturnType<typeof schedulingGetPreferences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSchedulingGetPreferences<TData = Awaited<ReturnType<typeof schedulingGetPreferences>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSchedulingGetPreferences<TData = Awaited<ReturnType<typeof schedulingGetPreferences>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetPreferences>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSchedulingGetPreferencesQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const schedulingUpdatePreferences = (
    schedulingUpdatePreferencesBody: SchedulingUpdatePreferencesBody,
 ) => {
      
      
      return customInstance<SchedulingUpdatePreferences200>(
      {url: `/scheduling/preferences`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: schedulingUpdatePreferencesBody
    },
      );
    }
  


export const getSchedulingUpdatePreferencesMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdatePreferences>>, TError,{data: SchedulingUpdatePreferencesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdatePreferences>>, TError,{data: SchedulingUpdatePreferencesBody}, TContext> => {

const mutationKey = ['schedulingUpdatePreferences'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof schedulingUpdatePreferences>>, {data: SchedulingUpdatePreferencesBody}> = (props) => {
          const {data} = props ?? {};

          return  schedulingUpdatePreferences(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SchedulingUpdatePreferencesMutationResult = NonNullable<Awaited<ReturnType<typeof schedulingUpdatePreferences>>>
    export type SchedulingUpdatePreferencesMutationBody = SchedulingUpdatePreferencesBody
    export type SchedulingUpdatePreferencesMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSchedulingUpdatePreferences = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdatePreferences>>, TError,{data: SchedulingUpdatePreferencesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof schedulingUpdatePreferences>>,
        TError,
        {data: SchedulingUpdatePreferencesBody},
        TContext
      > => {

      const mutationOptions = getSchedulingUpdatePreferencesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const schedulingGetSlots = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SchedulingGetSlots200>(
      {url: `/scheduling/slots`, method: 'GET', signal
    },
      );
    }
  

export const getSchedulingGetSlotsQueryKey = () => {
    return [`/scheduling/slots`] as const;
    }

    
export const getSchedulingGetSlotsQueryOptions = <TData = Awaited<ReturnType<typeof schedulingGetSlots>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSchedulingGetSlotsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof schedulingGetSlots>>> = ({ signal }) => schedulingGetSlots(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SchedulingGetSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof schedulingGetSlots>>>
export type SchedulingGetSlotsQueryError = AuthenticationExceptionResponse


export function useSchedulingGetSlots<TData = Awaited<ReturnType<typeof schedulingGetSlots>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulingGetSlots>>,
          TError,
          Awaited<ReturnType<typeof schedulingGetSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSchedulingGetSlots<TData = Awaited<ReturnType<typeof schedulingGetSlots>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulingGetSlots>>,
          TError,
          Awaited<ReturnType<typeof schedulingGetSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSchedulingGetSlots<TData = Awaited<ReturnType<typeof schedulingGetSlots>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSchedulingGetSlots<TData = Awaited<ReturnType<typeof schedulingGetSlots>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schedulingGetSlots>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSchedulingGetSlotsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const schedulingUpdateSlots = (
    schedulingUpdateSlotsBody: SchedulingUpdateSlotsBody,
 ) => {
      
      
      return customInstance<SchedulingUpdateSlots200>(
      {url: `/scheduling/slots`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: schedulingUpdateSlotsBody
    },
      );
    }
  


export const getSchedulingUpdateSlotsMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdateSlots>>, TError,{data: SchedulingUpdateSlotsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdateSlots>>, TError,{data: SchedulingUpdateSlotsBody}, TContext> => {

const mutationKey = ['schedulingUpdateSlots'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof schedulingUpdateSlots>>, {data: SchedulingUpdateSlotsBody}> = (props) => {
          const {data} = props ?? {};

          return  schedulingUpdateSlots(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SchedulingUpdateSlotsMutationResult = NonNullable<Awaited<ReturnType<typeof schedulingUpdateSlots>>>
    export type SchedulingUpdateSlotsMutationBody = SchedulingUpdateSlotsBody
    export type SchedulingUpdateSlotsMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useSchedulingUpdateSlots = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof schedulingUpdateSlots>>, TError,{data: SchedulingUpdateSlotsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof schedulingUpdateSlots>>,
        TError,
        {data: SchedulingUpdateSlotsBody},
        TContext
      > => {

      const mutationOptions = getSchedulingUpdateSlotsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    