/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Laravel
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  WebhookHandleWebhook200
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




/**
 * @summary Handle a Stripe webhook call
 */
export const webhookHandleWebhook = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<WebhookHandleWebhook200>(
      {url: `/stripe/webhook`, method: 'POST', signal
    },
      );
    }
  


export const getWebhookHandleWebhookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookHandleWebhook>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof webhookHandleWebhook>>, TError,void, TContext> => {

const mutationKey = ['webhookHandleWebhook'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookHandleWebhook>>, void> = () => {
          

          return  webhookHandleWebhook()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WebhookHandleWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof webhookHandleWebhook>>>
    
    export type WebhookHandleWebhookMutationError = unknown

    /**
 * @summary Handle a Stripe webhook call
 */
export const useWebhookHandleWebhook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookHandleWebhook>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookHandleWebhook>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getWebhookHandleWebhookMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    