/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Laravel
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
export interface ErrorResponse {
  /** Human-readable error message */
  error: string;
  /** Machine-readable error code */
  code: string;
  /** HTTP status code */
  status: number;
  details?: unknown;
}

export type AuthenticationExceptionResponse = {
  /** Error overview. */
  message: string;
};

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};

export type ValidationExceptionResponse = {
  /** Errors overview. */
  message: string;
  /** A detailed description of each field that failed validation. */
  errors: ValidationExceptionResponseErrors;
};

export type AdminUsageParams = {
from?: string;
to?: string;
};

export type AdminUsage200 = {
  usage: string;
};

export type AdminUpdateTrialBodyTrialEndsAt = string | null;

/**
 * @maxLength 500
 */
export type AdminUpdateTrialBodyTrialNotes = string | null;

export type AdminUpdateTrialBody = {
  trialEndsAt?: AdminUpdateTrialBodyTrialEndsAt;
  /** @maxLength 500 */
  trialNotes?: AdminUpdateTrialBodyTrialNotes;
};

export type AdminUpdateTrial200 = {
  user: string;
};

export type AdminUpdateTrial404Error = typeof AdminUpdateTrial404Error[keyof typeof AdminUpdateTrial404Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdateTrial404Error = {
  User_not_found: 'User not found',
} as const;

export type AdminUpdateTrial404Code = typeof AdminUpdateTrial404Code[keyof typeof AdminUpdateTrial404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdateTrial404Code = {
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type AdminUpdateTrial404Status = typeof AdminUpdateTrial404Status[keyof typeof AdminUpdateTrial404Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdateTrial404Status = {
  NUMBER_404: 404,
} as const;

export type AdminUpdateTrial404 = {
  error: AdminUpdateTrial404Error;
  code: AdminUpdateTrial404Code;
  status: AdminUpdateTrial404Status;
};

export type AuthMe200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type AuthMe200 = {
  user: AuthMe200User;
};

export type AuthLogout200 = {
  ok: boolean;
};

export type AuthLoginBody = {
  email: string;
  password: string;
  remember?: boolean;
};

export type AuthLogin200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type AuthLogin200 = {
  user: AuthLogin200User;
};

export type AuthRegisterBody = {
  email: string;
  /** @maxLength 255 */
  name: string;
  password: string;
};

export type AuthRegister200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type AuthRegister200 = {
  user: AuthRegister200User;
};

export type AuthRegister409Error = typeof AuthRegister409Error[keyof typeof AuthRegister409Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthRegister409Error = {
  Email_already_registered: 'Email already registered',
} as const;

export type AuthRegister409Code = typeof AuthRegister409Code[keyof typeof AuthRegister409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthRegister409Code = {
  CONFLICT: 'CONFLICT',
} as const;

export type AuthRegister409Status = typeof AuthRegister409Status[keyof typeof AuthRegister409Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthRegister409Status = {
  NUMBER_409: 409,
} as const;

export type AuthRegister409 = {
  error: AuthRegister409Error;
  code: AuthRegister409Code;
  status: AuthRegister409Status;
};

export type BillingCheckoutSession200 = {
  url: string;
};

export type BillingCheckoutSession503Error = typeof BillingCheckoutSession503Error[keyof typeof BillingCheckoutSession503Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillingCheckoutSession503Error = {
  Stripe_billing_is_not_fully_configured: 'Stripe billing is not fully configured',
} as const;

export type BillingCheckoutSession503 = {
  error: BillingCheckoutSession503Error;
};

export type BillingPortalSession200 = {
  url: string;
};

export type BillingPortalSession503Error = typeof BillingPortalSession503Error[keyof typeof BillingPortalSession503Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillingPortalSession503Error = {
  Billing_portal_return_URL_is_not_configured: 'Billing portal return URL is not configured',
} as const;

export type BillingPortalSession503 = {
  error: BillingPortalSession503Error;
};

export type BillingStatus200UserSubscriptionStatus = string | 'inactive';

export type BillingStatus200UserSubscriptionPlan = string | 'pro';

export type BillingStatus200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: BillingStatus200UserSubscriptionStatus;
  subscriptionPlan: BillingStatus200UserSubscriptionPlan;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type BillingStatus200 = {
  user: BillingStatus200User;
};

export type HealthIndex200Status = typeof HealthIndex200Status[keyof typeof HealthIndex200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthIndex200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;

export type HealthIndex200 = {
  status: HealthIndex200Status;
  timestamp: string;
  environment: string;
  database: string;
};

export type LinkedInAuth0200 = {
  url: string;
};

export type LinkedInAuth0422Error = typeof LinkedInAuth0422Error[keyof typeof LinkedInAuth0422Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Error = {
  LinkedIn_OAuth_is_not_configured: 'LinkedIn OAuth is not configured',
} as const;

export type LinkedInAuth0422Code = typeof LinkedInAuth0422Code[keyof typeof LinkedInAuth0422Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Code = {
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type LinkedInAuth0422Status = typeof LinkedInAuth0422Status[keyof typeof LinkedInAuth0422Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Status = {
  NUMBER_422: 422,
} as const;

export type LinkedInAuth0422 = {
  error: LinkedInAuth0422Error;
  code: LinkedInAuth0422Code;
  status: LinkedInAuth0422Status;
};

export type LinkedInCallback0Params = {
code?: string;
state?: string;
};

export type LinkedInCallback0200AnyOf = {
  connected: boolean;
};

export type LinkedInCallback0200 = string | LinkedInCallback0200AnyOf;

export type LinkedInCallback0400Error = typeof LinkedInCallback0400Error[keyof typeof LinkedInCallback0400Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Error = {
  LinkedIn_callback_failed: 'LinkedIn callback failed',
} as const;

export type LinkedInCallback0400Code = typeof LinkedInCallback0400Code[keyof typeof LinkedInCallback0400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Code = {
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type LinkedInCallback0400Status = typeof LinkedInCallback0400Status[keyof typeof LinkedInCallback0400Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Status = {
  NUMBER_400: 400,
} as const;

export type LinkedInCallback0400 = {
  error: LinkedInCallback0400Error;
  code: LinkedInCallback0400Code;
  status: LinkedInCallback0400Status;
};

export type LinkedInStatus200 = {
  connected: boolean;
};

export type LinkedInDisconnect200 = {
  connected: boolean;
};

export type LinkedInAuth0200 = {
  url: string;
};

export type LinkedInAuth0422Error = typeof LinkedInAuth0422Error[keyof typeof LinkedInAuth0422Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Error = {
  LinkedIn_OAuth_is_not_configured: 'LinkedIn OAuth is not configured',
} as const;

export type LinkedInAuth0422Code = typeof LinkedInAuth0422Code[keyof typeof LinkedInAuth0422Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Code = {
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type LinkedInAuth0422Status = typeof LinkedInAuth0422Status[keyof typeof LinkedInAuth0422Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInAuth0422Status = {
  NUMBER_422: 422,
} as const;

export type LinkedInAuth0422 = {
  error: LinkedInAuth0422Error;
  code: LinkedInAuth0422Code;
  status: LinkedInAuth0422Status;
};

export type LinkedInCallback0200AnyOf = {
  connected: boolean;
};

export type LinkedInCallback0200 = string | LinkedInCallback0200AnyOf;

export type LinkedInCallback0400Error = typeof LinkedInCallback0400Error[keyof typeof LinkedInCallback0400Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Error = {
  LinkedIn_callback_failed: 'LinkedIn callback failed',
} as const;

export type LinkedInCallback0400Code = typeof LinkedInCallback0400Code[keyof typeof LinkedInCallback0400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Code = {
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type LinkedInCallback0400Status = typeof LinkedInCallback0400Status[keyof typeof LinkedInCallback0400Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkedInCallback0400Status = {
  NUMBER_400: 400,
} as const;

export type LinkedInCallback0400 = {
  error: LinkedInCallback0400Error;
  code: LinkedInCallback0400Code;
  status: LinkedInCallback0400Status;
};

export type PostsFrameworks200FrameworksItem0Id = typeof PostsFrameworks200FrameworksItem0Id[keyof typeof PostsFrameworks200FrameworksItem0Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0Id = {
  'problem-agitate': 'problem-agitate',
} as const;

export type PostsFrameworks200FrameworksItem0Label = typeof PostsFrameworks200FrameworksItem0Label[keyof typeof PostsFrameworks200FrameworksItem0Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0Label = {
  'Problem_→_Agitate': 'Problem → Agitate',
} as const;

export type PostsFrameworks200FrameworksItem0Description = typeof PostsFrameworks200FrameworksItem0Description[keyof typeof PostsFrameworks200FrameworksItem0Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0Description = {
  'Start_with_the_painful_status_quo,_then_intensify_it_with_a_consequence_that_creates_urgency_to_keep_reading': 'Start with the painful status quo, then intensify it with a consequence that creates urgency to keep reading.',
} as const;

export type PostsFrameworks200FrameworksItem0Example = typeof PostsFrameworks200FrameworksItem0Example[keyof typeof PostsFrameworks200FrameworksItem0Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0Example = {
  'Most_coaches_post_daily_and_still_hear_crickets_Here’s_the_brutal_reason_no_one_told_you': 'Most coaches post daily and still hear crickets. Here’s the brutal reason no one told you.',
} as const;

export type PostsFrameworks200FrameworksItem0TagsItem0 = typeof PostsFrameworks200FrameworksItem0TagsItem0[keyof typeof PostsFrameworks200FrameworksItem0TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0TagsItem0 = {
  pain: 'pain',
} as const;

export type PostsFrameworks200FrameworksItem0TagsItem1 = typeof PostsFrameworks200FrameworksItem0TagsItem1[keyof typeof PostsFrameworks200FrameworksItem0TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem0TagsItem1 = {
  urgency: 'urgency',
} as const;

export type PostsFrameworks200FrameworksItem0 = {
  id: PostsFrameworks200FrameworksItem0Id;
  label: PostsFrameworks200FrameworksItem0Label;
  description: PostsFrameworks200FrameworksItem0Description;
  example: PostsFrameworks200FrameworksItem0Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem0TagsItem0, PostsFrameworks200FrameworksItem0TagsItem1];
};

export type PostsFrameworks200FrameworksItem1Id = typeof PostsFrameworks200FrameworksItem1Id[keyof typeof PostsFrameworks200FrameworksItem1Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1Id = {
  'contrarian-flip': 'contrarian-flip',
} as const;

export type PostsFrameworks200FrameworksItem1Label = typeof PostsFrameworks200FrameworksItem1Label[keyof typeof PostsFrameworks200FrameworksItem1Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1Label = {
  Contrarian_Flip: 'Contrarian Flip',
} as const;

export type PostsFrameworks200FrameworksItem1Description = typeof PostsFrameworks200FrameworksItem1Description[keyof typeof PostsFrameworks200FrameworksItem1Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1Description = {
  Challenge_a_common_belief_with_a_bold_reversal_that_signals_you_are_about_to_reveal_a_better_path_forward: 'Challenge a common belief with a bold reversal that signals you are about to reveal a better path forward.',
} as const;

export type PostsFrameworks200FrameworksItem1Example = typeof PostsFrameworks200FrameworksItem1Example[keyof typeof PostsFrameworks200FrameworksItem1Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1Example = {
  'The_worst_advice_in_coaching?_“Nurture_every_lead”_Here’s_why_that’s_killing_your_pipeline': 'The worst advice in coaching? “Nurture every lead.” Here’s why that’s killing your pipeline.',
} as const;

export type PostsFrameworks200FrameworksItem1TagsItem0 = typeof PostsFrameworks200FrameworksItem1TagsItem0[keyof typeof PostsFrameworks200FrameworksItem1TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1TagsItem0 = {
  contrarian: 'contrarian',
} as const;

export type PostsFrameworks200FrameworksItem1TagsItem1 = typeof PostsFrameworks200FrameworksItem1TagsItem1[keyof typeof PostsFrameworks200FrameworksItem1TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem1TagsItem1 = {
  pattern_interrupt: 'pattern interrupt',
} as const;

export type PostsFrameworks200FrameworksItem1 = {
  id: PostsFrameworks200FrameworksItem1Id;
  label: PostsFrameworks200FrameworksItem1Label;
  description: PostsFrameworks200FrameworksItem1Description;
  example: PostsFrameworks200FrameworksItem1Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem1TagsItem0, PostsFrameworks200FrameworksItem1TagsItem1];
};

export type PostsFrameworks200FrameworksItem2Id = typeof PostsFrameworks200FrameworksItem2Id[keyof typeof PostsFrameworks200FrameworksItem2Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2Id = {
  'data-jolt': 'data-jolt',
} as const;

export type PostsFrameworks200FrameworksItem2Label = typeof PostsFrameworks200FrameworksItem2Label[keyof typeof PostsFrameworks200FrameworksItem2Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2Label = {
  Data_Jolt: 'Data Jolt',
} as const;

export type PostsFrameworks200FrameworksItem2Description = typeof PostsFrameworks200FrameworksItem2Description[keyof typeof PostsFrameworks200FrameworksItem2Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2Description = {
  Lead_with_a_specific_metric_or_contrast_that_reframes_the_opportunity_or_risk_in_unmistakable_numbers: 'Lead with a specific metric or contrast that reframes the opportunity or risk in unmistakable numbers.',
} as const;

export type PostsFrameworks200FrameworksItem2Example = typeof PostsFrameworks200FrameworksItem2Example[keyof typeof PostsFrameworks200FrameworksItem2Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2Example = {
  '87%_of_our_inbound_leads_ghosted…_until_we_changed_one_sentence_in_our_opener': '87% of our inbound leads ghosted… until we changed one sentence in our opener.',
} as const;

export type PostsFrameworks200FrameworksItem2TagsItem0 = typeof PostsFrameworks200FrameworksItem2TagsItem0[keyof typeof PostsFrameworks200FrameworksItem2TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2TagsItem0 = {
  proof: 'proof',
} as const;

export type PostsFrameworks200FrameworksItem2TagsItem1 = typeof PostsFrameworks200FrameworksItem2TagsItem1[keyof typeof PostsFrameworks200FrameworksItem2TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem2TagsItem1 = {
  specificity: 'specificity',
} as const;

export type PostsFrameworks200FrameworksItem2 = {
  id: PostsFrameworks200FrameworksItem2Id;
  label: PostsFrameworks200FrameworksItem2Label;
  description: PostsFrameworks200FrameworksItem2Description;
  example: PostsFrameworks200FrameworksItem2Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem2TagsItem0, PostsFrameworks200FrameworksItem2TagsItem1];
};

export type PostsFrameworks200FrameworksItem3Id = typeof PostsFrameworks200FrameworksItem3Id[keyof typeof PostsFrameworks200FrameworksItem3Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3Id = {
  'confession-to-lesson': 'confession-to-lesson',
} as const;

export type PostsFrameworks200FrameworksItem3Label = typeof PostsFrameworks200FrameworksItem3Label[keyof typeof PostsFrameworks200FrameworksItem3Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3Label = {
  'Confession_→_Lesson': 'Confession → Lesson',
} as const;

export type PostsFrameworks200FrameworksItem3Description = typeof PostsFrameworks200FrameworksItem3Description[keyof typeof PostsFrameworks200FrameworksItem3Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3Description = {
  'Offer_a_vulnerable_admission_or_mistake_that_earns_trust,_then_hint_at_the_transformation_you_unlocked': 'Offer a vulnerable admission or mistake that earns trust, then hint at the transformation you unlocked.',
} as const;

export type PostsFrameworks200FrameworksItem3Example = typeof PostsFrameworks200FrameworksItem3Example[keyof typeof PostsFrameworks200FrameworksItem3Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3Example = {
  I_almost_shut_down_my_practice_last_year_The_fix_took_12_minutes_a_week: 'I almost shut down my practice last year. The fix took 12 minutes a week.',
} as const;

export type PostsFrameworks200FrameworksItem3TagsItem0 = typeof PostsFrameworks200FrameworksItem3TagsItem0[keyof typeof PostsFrameworks200FrameworksItem3TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3TagsItem0 = {
  story: 'story',
} as const;

export type PostsFrameworks200FrameworksItem3TagsItem1 = typeof PostsFrameworks200FrameworksItem3TagsItem1[keyof typeof PostsFrameworks200FrameworksItem3TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem3TagsItem1 = {
  vulnerability: 'vulnerability',
} as const;

export type PostsFrameworks200FrameworksItem3 = {
  id: PostsFrameworks200FrameworksItem3Id;
  label: PostsFrameworks200FrameworksItem3Label;
  description: PostsFrameworks200FrameworksItem3Description;
  example: PostsFrameworks200FrameworksItem3Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem3TagsItem0, PostsFrameworks200FrameworksItem3TagsItem1];
};

export type PostsFrameworks200FrameworksItem4Id = typeof PostsFrameworks200FrameworksItem4Id[keyof typeof PostsFrameworks200FrameworksItem4Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4Id = {
  'myth-bust': 'myth-bust',
} as const;

export type PostsFrameworks200FrameworksItem4Label = typeof PostsFrameworks200FrameworksItem4Label[keyof typeof PostsFrameworks200FrameworksItem4Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4Label = {
  Myth_Bust: 'Myth Bust',
} as const;

export type PostsFrameworks200FrameworksItem4Description = typeof PostsFrameworks200FrameworksItem4Description[keyof typeof PostsFrameworks200FrameworksItem4Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4Description = {
  'Expose_a_beloved_industry_myth,_then_tease_the_unexpected_truth_that_flips_the_audience’s_worldview': 'Expose a beloved industry myth, then tease the unexpected truth that flips the audience’s worldview.',
} as const;

export type PostsFrameworks200FrameworksItem4Example = typeof PostsFrameworks200FrameworksItem4Example[keyof typeof PostsFrameworks200FrameworksItem4Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4Example = {
  '“Add_more_value”_is_not_why_prospects_ignore_you_This_is': '“Add more value” is not why prospects ignore you. This is.',
} as const;

export type PostsFrameworks200FrameworksItem4TagsItem0 = typeof PostsFrameworks200FrameworksItem4TagsItem0[keyof typeof PostsFrameworks200FrameworksItem4TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4TagsItem0 = {
  belief_shift: 'belief shift',
} as const;

export type PostsFrameworks200FrameworksItem4TagsItem1 = typeof PostsFrameworks200FrameworksItem4TagsItem1[keyof typeof PostsFrameworks200FrameworksItem4TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem4TagsItem1 = {
  clarity: 'clarity',
} as const;

export type PostsFrameworks200FrameworksItem4 = {
  id: PostsFrameworks200FrameworksItem4Id;
  label: PostsFrameworks200FrameworksItem4Label;
  description: PostsFrameworks200FrameworksItem4Description;
  example: PostsFrameworks200FrameworksItem4Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem4TagsItem0, PostsFrameworks200FrameworksItem4TagsItem1];
};

export type PostsFrameworks200FrameworksItem5Id = typeof PostsFrameworks200FrameworksItem5Id[keyof typeof PostsFrameworks200FrameworksItem5Id];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5Id = {
  'micro-case': 'micro-case',
} as const;

export type PostsFrameworks200FrameworksItem5Label = typeof PostsFrameworks200FrameworksItem5Label[keyof typeof PostsFrameworks200FrameworksItem5Label];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5Label = {
  Micro_Case_Study: 'Micro Case Study',
} as const;

export type PostsFrameworks200FrameworksItem5Description = typeof PostsFrameworks200FrameworksItem5Description[keyof typeof PostsFrameworks200FrameworksItem5Description];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5Description = {
  'Compress_a_before→after_story_into_two_lines_that_prove_you_can_create_the_transformation_your_audience_craves': 'Compress a before→after story into two lines that prove you can create the transformation your audience craves.',
} as const;

export type PostsFrameworks200FrameworksItem5Example = typeof PostsFrameworks200FrameworksItem5Example[keyof typeof PostsFrameworks200FrameworksItem5Example];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5Example = {
  'Session_1:_14%_close_rate_Session_6:_61%_Same_offer_Different_first_sentence': 'Session 1: 14% close rate. Session 6: 61%. Same offer. Different first sentence.',
} as const;

export type PostsFrameworks200FrameworksItem5TagsItem0 = typeof PostsFrameworks200FrameworksItem5TagsItem0[keyof typeof PostsFrameworks200FrameworksItem5TagsItem0];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5TagsItem0 = {
  credibility: 'credibility',
} as const;

export type PostsFrameworks200FrameworksItem5TagsItem1 = typeof PostsFrameworks200FrameworksItem5TagsItem1[keyof typeof PostsFrameworks200FrameworksItem5TagsItem1];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsFrameworks200FrameworksItem5TagsItem1 = {
  outcomes: 'outcomes',
} as const;

export type PostsFrameworks200FrameworksItem5 = {
  id: PostsFrameworks200FrameworksItem5Id;
  label: PostsFrameworks200FrameworksItem5Label;
  description: PostsFrameworks200FrameworksItem5Description;
  example: PostsFrameworks200FrameworksItem5Example;
  /**
   * @minItems 2
   * @maxItems 2
   */
  tags: [PostsFrameworks200FrameworksItem5TagsItem0, PostsFrameworks200FrameworksItem5TagsItem1];
};

export type PostsFrameworks200 = {
  /**
   * @minItems 6
   * @maxItems 6
   */
  frameworks: [PostsFrameworks200FrameworksItem0, PostsFrameworks200FrameworksItem1, PostsFrameworks200FrameworksItem2, PostsFrameworks200FrameworksItem3, PostsFrameworks200FrameworksItem4, PostsFrameworks200FrameworksItem5];
};

export type PostsListByProjectParams = {
/**
 * @minimum 1
 */
page?: number | null;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number | null;
};

export type PostsListByProject200ItemsItemInsightId = string | null;

export type PostsListByProject200ItemsItemPublishedAt = string | null;

export type PostsListByProject200ItemsItemScheduledAt = string | null;

export type PostsListByProject200ItemsItemScheduleStatus = string | null;

export type PostsListByProject200ItemsItemScheduleError = string | null;

export type PostsListByProject200ItemsItemScheduleAttemptedAt = string | null;

export type PostsListByProject200ItemsItem = {
  id: string;
  projectId: string;
  insightId: PostsListByProject200ItemsItemInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsListByProject200ItemsItemPublishedAt;
  scheduledAt: PostsListByProject200ItemsItemScheduledAt;
  scheduleStatus: PostsListByProject200ItemsItemScheduleStatus;
  scheduleError: PostsListByProject200ItemsItemScheduleError;
  scheduleAttemptedAt: PostsListByProject200ItemsItemScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsListByProject200Meta = {
  page: number;
  pageSize: number;
  total: number;
};

export type PostsListByProject200 = {
  items: PostsListByProject200ItemsItem[];
  meta: PostsListByProject200Meta;
};

export type PostsListScheduledParams = {
/**
 * @minimum 1
 */
page?: number | null;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number | null;
status?: string | null;
};

export type PostsListScheduled200ItemsItemInsightId = string | null;

export type PostsListScheduled200ItemsItemPublishedAt = string | null;

export type PostsListScheduled200ItemsItemScheduledAt = string | null;

export type PostsListScheduled200ItemsItemScheduleStatus = string | null;

export type PostsListScheduled200ItemsItemScheduleError = string | null;

export type PostsListScheduled200ItemsItemScheduleAttemptedAt = string | null;

export type PostsListScheduled200ItemsItem = {
  id: string;
  projectId: string;
  insightId: PostsListScheduled200ItemsItemInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsListScheduled200ItemsItemPublishedAt;
  scheduledAt: PostsListScheduled200ItemsItemScheduledAt;
  scheduleStatus: PostsListScheduled200ItemsItemScheduleStatus;
  scheduleError: PostsListScheduled200ItemsItemScheduleError;
  scheduleAttemptedAt: PostsListScheduled200ItemsItemScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsListScheduled200Meta = {
  page: number;
  pageSize: number;
  total: number;
};

export type PostsListScheduled200 = {
  items: PostsListScheduled200ItemsItem[];
  meta: PostsListScheduled200Meta;
};

export type PostsAnalyticsParams = {
/**
 * @minimum 1
 * @maximum 365
 */
days?: number | null;
};

export type PostsAnalytics200SummaryStatusCounts = {
  pending: string;
  approved: string;
  rejected: string;
  published: string;
};

export type PostsAnalytics200SummaryScheduledCount = typeof PostsAnalytics200SummaryScheduledCount[keyof typeof PostsAnalytics200SummaryScheduledCount];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsAnalytics200SummaryScheduledCount = {
  NUMBER_0: 0,
} as const;

export type PostsAnalytics200SummaryPublishedInPeriod = typeof PostsAnalytics200SummaryPublishedInPeriod[keyof typeof PostsAnalytics200SummaryPublishedInPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsAnalytics200SummaryPublishedInPeriod = {
  NUMBER_0: 0,
} as const;

export type PostsAnalytics200SummaryAverageTimeToPublishHours = string | null;

export type PostsAnalytics200Summary = {
  totalPosts: string;
  statusCounts: PostsAnalytics200SummaryStatusCounts;
  scheduledCount: PostsAnalytics200SummaryScheduledCount;
  publishedInPeriod: PostsAnalytics200SummaryPublishedInPeriod;
  averageTimeToPublishHours: PostsAnalytics200SummaryAverageTimeToPublishHours;
  rangeDays: number;
};

export type PostsAnalytics200 = {
  summary: PostsAnalytics200Summary;
  daily: string;
  /**
   * @minItems 0
   * @maxItems 0
   */
  topHashtags: string[];
};

export type PostsGet200PostInsightId = string | null;

export type PostsGet200PostPublishedAt = string | null;

export type PostsGet200PostScheduledAt = string | null;

export type PostsGet200PostScheduleStatus = string | null;

export type PostsGet200PostScheduleError = string | null;

export type PostsGet200PostScheduleAttemptedAt = string | null;

export type PostsGet200Post = {
  id: string;
  projectId: string;
  insightId: PostsGet200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsGet200PostPublishedAt;
  scheduledAt: PostsGet200PostScheduledAt;
  scheduleStatus: PostsGet200PostScheduleStatus;
  scheduleError: PostsGet200PostScheduleError;
  scheduleAttemptedAt: PostsGet200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsGet200 = {
  post: PostsGet200Post;
};

export type PostsUpdateBodyContent = string | null;

export type PostsUpdateBodyHashtags = string[] | null;

export type PostsUpdateBodyStatus = string | null;

export type PostsUpdateBody = {
  content?: PostsUpdateBodyContent;
  hashtags?: PostsUpdateBodyHashtags;
  status?: PostsUpdateBodyStatus;
};

export type PostsUpdate200PostInsightId = string | null;

export type PostsUpdate200PostPublishedAt = string | null;

export type PostsUpdate200PostScheduledAt = string | null;

export type PostsUpdate200PostScheduleStatus = string | null;

export type PostsUpdate200PostScheduleError = string | null;

export type PostsUpdate200PostScheduleAttemptedAt = string | null;

export type PostsUpdate200Post = {
  id: string;
  projectId: string;
  insightId: PostsUpdate200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsUpdate200PostPublishedAt;
  scheduledAt: PostsUpdate200PostScheduledAt;
  scheduleStatus: PostsUpdate200PostScheduleStatus;
  scheduleError: PostsUpdate200PostScheduleError;
  scheduleAttemptedAt: PostsUpdate200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsUpdate200 = {
  post: PostsUpdate200Post;
};

export type PostsPublishNow200PostInsightId = string | null;

export type PostsPublishNow200PostPublishedAt = string | null;

export type PostsPublishNow200PostScheduledAt = string | null;

export type PostsPublishNow200PostScheduleStatus = string | null;

export type PostsPublishNow200PostScheduleError = string | null;

export type PostsPublishNow200PostScheduleAttemptedAt = string | null;

export type PostsPublishNow200Post = {
  id: string;
  projectId: string;
  insightId: PostsPublishNow200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsPublishNow200PostPublishedAt;
  scheduledAt: PostsPublishNow200PostScheduledAt;
  scheduleStatus: PostsPublishNow200PostScheduleStatus;
  scheduleError: PostsPublishNow200PostScheduleError;
  scheduleAttemptedAt: PostsPublishNow200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsPublishNow200 = {
  post: PostsPublishNow200Post;
};

export type PostsScheduleBody = {
  scheduledAt: string;
};

export type PostsSchedule200PostInsightId = string | null;

export type PostsSchedule200PostPublishedAt = string | null;

export type PostsSchedule200PostScheduledAt = string | null;

export type PostsSchedule200PostScheduleStatus = string | null;

export type PostsSchedule200PostScheduleError = string | null;

export type PostsSchedule200PostScheduleAttemptedAt = string | null;

export type PostsSchedule200Post = {
  id: string;
  projectId: string;
  insightId: PostsSchedule200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsSchedule200PostPublishedAt;
  scheduledAt: PostsSchedule200PostScheduledAt;
  scheduleStatus: PostsSchedule200PostScheduleStatus;
  scheduleError: PostsSchedule200PostScheduleError;
  scheduleAttemptedAt: PostsSchedule200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsSchedule200 = {
  post: PostsSchedule200Post;
};

export type PostsUnschedule200PostInsightId = string | null;

export type PostsUnschedule200PostPublishedAt = string | null;

export type PostsUnschedule200PostScheduledAt = string | null;

export type PostsUnschedule200PostScheduleStatus = string | null;

export type PostsUnschedule200PostScheduleError = string | null;

export type PostsUnschedule200PostScheduleAttemptedAt = string | null;

export type PostsUnschedule200Post = {
  id: string;
  projectId: string;
  insightId: PostsUnschedule200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsUnschedule200PostPublishedAt;
  scheduledAt: PostsUnschedule200PostScheduledAt;
  scheduleStatus: PostsUnschedule200PostScheduleStatus;
  scheduleError: PostsUnschedule200PostScheduleError;
  scheduleAttemptedAt: PostsUnschedule200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsUnschedule200 = {
  post: PostsUnschedule200Post;
};

export type PostsAutoSchedule200PostInsightId = string | null;

export type PostsAutoSchedule200PostPublishedAt = string | null;

export type PostsAutoSchedule200PostScheduledAt = string | null;

export type PostsAutoSchedule200PostScheduleStatus = string | null;

export type PostsAutoSchedule200PostScheduleError = string | null;

export type PostsAutoSchedule200PostScheduleAttemptedAt = string | null;

export type PostsAutoSchedule200Post = {
  id: string;
  projectId: string;
  insightId: PostsAutoSchedule200PostInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsAutoSchedule200PostPublishedAt;
  scheduledAt: PostsAutoSchedule200PostScheduledAt;
  scheduleStatus: PostsAutoSchedule200PostScheduleStatus;
  scheduleError: PostsAutoSchedule200PostScheduleError;
  scheduleAttemptedAt: PostsAutoSchedule200PostScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsAutoSchedule200 = {
  post: PostsAutoSchedule200Post;
};

/**
 * @minimum 1
 * @maximum 200
 */
export type PostsAutoScheduleProjectBodyLimit = number | null;

export type PostsAutoScheduleProjectBody = {
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: PostsAutoScheduleProjectBodyLimit;
};

export type PostsAutoScheduleProject200ScheduledItemInsightId = string | null;

export type PostsAutoScheduleProject200ScheduledItemPublishedAt = string | null;

export type PostsAutoScheduleProject200ScheduledItemScheduledAt = string | null;

export type PostsAutoScheduleProject200ScheduledItemScheduleStatus = string | null;

export type PostsAutoScheduleProject200ScheduledItemScheduleError = string | null;

export type PostsAutoScheduleProject200ScheduledItemScheduleAttemptedAt = string | null;

export type PostsAutoScheduleProject200ScheduledItem = {
  id: string;
  projectId: string;
  insightId: PostsAutoScheduleProject200ScheduledItemInsightId;
  content: string;
  hashtags: string[];
  platform: string;
  status: string;
  publishedAt: PostsAutoScheduleProject200ScheduledItemPublishedAt;
  scheduledAt: PostsAutoScheduleProject200ScheduledItemScheduledAt;
  scheduleStatus: PostsAutoScheduleProject200ScheduledItemScheduleStatus;
  scheduleError: PostsAutoScheduleProject200ScheduledItemScheduleError;
  scheduleAttemptedAt: PostsAutoScheduleProject200ScheduledItemScheduleAttemptedAt;
  createdAt: string;
  updatedAt: string;
};

export type PostsAutoScheduleProject200Meta = {
  requested: number;
  scheduledCount: number;
};

export type PostsAutoScheduleProject200 = {
  scheduled: PostsAutoScheduleProject200ScheduledItem[];
  meta: PostsAutoScheduleProject200Meta;
};

export type PostsBulkSetStatusBody = {
  /** @minItems 1 */
  ids: string[];
  status: string;
};

export type PostsBulkSetStatus200AnyOf = {
  updated: string;
  items: string;
};

export type PostsBulkSetStatus200AnyOfTwoUpdated = typeof PostsBulkSetStatus200AnyOfTwoUpdated[keyof typeof PostsBulkSetStatus200AnyOfTwoUpdated];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsBulkSetStatus200AnyOfTwoUpdated = {
  NUMBER_0: 0,
} as const;

export type PostsBulkSetStatus200AnyOfTwo = {
  updated: PostsBulkSetStatus200AnyOfTwoUpdated;
  /**
   * @minItems 0
   * @maxItems 0
   */
  items: string[];
};

export type PostsBulkSetStatus200 = PostsBulkSetStatus200AnyOf | PostsBulkSetStatus200AnyOfTwo;

export type PostsBulkRegenerateBodyCustomInstructions = string | null;

export type PostsBulkRegenerateBody = {
  customInstructions?: PostsBulkRegenerateBodyCustomInstructions;
  /** @minItems 1 */
  ids: string[];
};

export type PostsBulkRegenerate200AnyOf = {
  updated: string;
  /**
   * @minItems 0
   * @maxItems 0
   */
  items: string[];
};

export type PostsBulkRegenerate200AnyOfTwoUpdated = typeof PostsBulkRegenerate200AnyOfTwoUpdated[keyof typeof PostsBulkRegenerate200AnyOfTwoUpdated];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostsBulkRegenerate200AnyOfTwoUpdated = {
  NUMBER_0: 0,
} as const;

export type PostsBulkRegenerate200AnyOfTwo = {
  updated: PostsBulkRegenerate200AnyOfTwoUpdated;
  /**
   * @minItems 0
   * @maxItems 0
   */
  items: string[];
};

export type PostsBulkRegenerate200 = PostsBulkRegenerate200AnyOf | PostsBulkRegenerate200AnyOfTwo;

export type PostsHookWorkbenchBodyFrameworkIds = string[] | null;

export type PostsHookWorkbenchBodyCustomFocus = string | null;

/**
 * @minimum 3
 * @maximum 5
 */
export type PostsHookWorkbenchBodyCount = number | null;

export type PostsHookWorkbenchBody = {
  frameworkIds?: PostsHookWorkbenchBodyFrameworkIds;
  customFocus?: PostsHookWorkbenchBodyCustomFocus;
  /**
   * @minimum 3
   * @maximum 5
   */
  count?: PostsHookWorkbenchBodyCount;
};

export type PostsHookWorkbench200HooksItem0 = {
  id: string;
  frameworkId: string;
  label: string;
  hook: string;
  curiosity: string;
  valueAlignment: string;
  rationale: string;
};

export type PostsHookWorkbench200Summary = string | null;

export type PostsHookWorkbench200 = {
  /**
   * @minItems 1
   * @maxItems 1
   */
  hooks: [PostsHookWorkbench200HooksItem0];
  summary: PostsHookWorkbench200Summary;
  recommendedId: string;
  generatedAt: string;
};

/**
 * @maxLength 255
 */
export type ProjectsCreateBodyTitle = string | null;

export type ProjectsCreateBody = {
  /** @maxLength 255 */
  title?: ProjectsCreateBodyTitle;
  transcript: string;
};

export type ProjectsCreate201Project = {
  id: string;
  userId: string;
  title: string;
  sourceUrl: string;
  currentStage: string;
  processingProgress: string;
  processingStep: string;
  createdAt: string;
  updatedAt: string;
};

export type ProjectsCreate201 = {
  project: ProjectsCreate201Project;
};

export type ProjectsListParams = {
/**
 * @minimum 1
 */
page?: number | null;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number | null;
stage?: string | null;
q?: string | null;
};

export type ProjectsList200Meta = {
  page: number;
  pageSize: number;
  total: string;
};

export type ProjectsList200 = {
  items: string;
  meta: ProjectsList200Meta;
};

export type ProjectsGet200Project = {
  id: string;
  userId: string;
  title: string;
  sourceUrl: string;
  currentStage: string;
  processingProgress: string;
  processingStep: string;
  createdAt: string;
  updatedAt: string;
};

export type ProjectsGet200 = {
  project: ProjectsGet200Project;
};

/**
 * @maxLength 255
 */
export type ProjectsUpdateBodyTitle = string | null;

export type ProjectsUpdateBodyTranscript = string | null;

export type ProjectsUpdateBody = {
  /** @maxLength 255 */
  title?: ProjectsUpdateBodyTitle;
  transcript?: ProjectsUpdateBodyTranscript;
};

export type ProjectsUpdate200Project = {
  id: string;
  userId: string;
  title: string;
  sourceUrl: string;
  currentStage: string;
  processingProgress: string;
  processingStep: string;
  createdAt: string;
  updatedAt: string;
};

export type ProjectsUpdate200 = {
  project: ProjectsUpdate200Project;
};

export type ProjectsStatus200Project = {
  currentStage: string;
  processingProgress: string;
  processingStep: string;
};

export type ProjectsStatus200 = {
  project: ProjectsStatus200Project;
};

export type ProjectsUpdateStageBodyNextStage = typeof ProjectsUpdateStageBodyNextStage[keyof typeof ProjectsUpdateStageBodyNextStage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsUpdateStageBodyNextStage = {
  processing: 'processing',
  posts: 'posts',
  ready: 'ready',
} as const;

export type ProjectsUpdateStageBody = {
  nextStage: ProjectsUpdateStageBodyNextStage;
};

export type ProjectsUpdateStage200Project = {
  id: string;
  userId: string;
  title: string;
  sourceUrl: string;
  currentStage: string;
  processingProgress: string;
  processingStep: string;
  createdAt: string;
  updatedAt: string;
};

export type ProjectsUpdateStage200 = {
  project: ProjectsUpdateStage200Project;
};

export type ProjectsProcess202ProjectCurrentStage = typeof ProjectsProcess202ProjectCurrentStage[keyof typeof ProjectsProcess202ProjectCurrentStage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess202ProjectCurrentStage = {
  processing: 'processing',
} as const;

export type ProjectsProcess202ProjectProcessingStep = typeof ProjectsProcess202ProjectProcessingStep[keyof typeof ProjectsProcess202ProjectProcessingStep];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess202ProjectProcessingStep = {
  queued: 'queued',
} as const;

export type ProjectsProcess202ProjectProcessingProgress = typeof ProjectsProcess202ProjectProcessingProgress[keyof typeof ProjectsProcess202ProjectProcessingProgress];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess202ProjectProcessingProgress = {
  NUMBER_0: 0,
} as const;

export type ProjectsProcess202Project = {
  currentStage: ProjectsProcess202ProjectCurrentStage;
  processingStep: ProjectsProcess202ProjectProcessingStep;
  processingProgress: ProjectsProcess202ProjectProcessingProgress;
};

export type ProjectsProcess202 = {
  queued: boolean;
  project: ProjectsProcess202Project;
};

export type ProjectsProcess409Error = typeof ProjectsProcess409Error[keyof typeof ProjectsProcess409Error];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess409Error = {
  Project_is_already_being_processed: 'Project is already being processed',
} as const;

export type ProjectsProcess409Code = typeof ProjectsProcess409Code[keyof typeof ProjectsProcess409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess409Code = {
  ALREADY_PROCESSING: 'ALREADY_PROCESSING',
} as const;

export type ProjectsProcess409Status = typeof ProjectsProcess409Status[keyof typeof ProjectsProcess409Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsProcess409Status = {
  NUMBER_409: 409,
} as const;

export type ProjectsProcess409 = {
  error: ProjectsProcess409Error;
  code: ProjectsProcess409Code;
  status: ProjectsProcess409Status;
};

export type SchedulingGetPreferences200Preferences = {
  timezone: string;
  leadTimeMinutes: number;
};

export type SchedulingGetPreferences200 = {
  preferences: SchedulingGetPreferences200Preferences;
};

export type SchedulingUpdatePreferencesBody = {
  timezone: string;
  /**
   * @minimum 0
   * @maximum 1440
   */
  leadTimeMinutes: number;
};

export type SchedulingUpdatePreferences200Preferences = {
  timezone: string;
  leadTimeMinutes: string;
};

export type SchedulingUpdatePreferences200 = {
  preferences: SchedulingUpdatePreferences200Preferences;
};

export type SchedulingGetSlots200 = {
  items: string;
};

export type SchedulingUpdateSlotsBody = {
  /** @minItems 1 */
  items: string[];
};

export type SchedulingUpdateSlots200 = {
  items: string;
};

export type SettingsProfile200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type SettingsProfile200 = {
  user: SettingsProfile200User;
};

/**
 * @maxLength 255
 */
export type SettingsUpdateProfileBodyName = string | null;

export type SettingsUpdateProfileBodyEmail = string | null;

export type SettingsUpdateProfileBody = {
  /** @maxLength 255 */
  name?: SettingsUpdateProfileBodyName;
  email?: SettingsUpdateProfileBodyEmail;
};

export type SettingsUpdateProfile200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type SettingsUpdateProfile200 = {
  user: SettingsUpdateProfile200User;
};

export type SettingsUpdatePasswordBody = {
  currentPassword: string;
  newPassword: string;
  newPasswordConfirmation: string;
};

export type SettingsUpdatePassword200User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  subscriptionStatus: string;
  subscriptionPlan: string;
  subscriptionCurrentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: string;
  trialNotes: string;
};

export type SettingsUpdatePassword200 = {
  user: SettingsUpdatePassword200User;
};

export type SettingsGetStyle200 = {
  style: string;
};

export type SettingsPutStyleBody = {
  style: string[];
};

export type SettingsPutStyle200 = {
  style: string;
};

export type TranscriptsPreviewBody = {
  transcript: string;
};

export type TranscriptsGet200 = {
  transcript: string;
};

export type TranscriptsPutBody = {
  transcript: string;
};

export type TranscriptsPut200 = {
  transcript: string;
};

export type WebhookHandleWebhook200AnyOf = { [key: string]: unknown };

export type WebhookHandleWebhook200 = WebhookHandleWebhook200AnyOf | string;

