/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Vox Prismatic
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthIndex200
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const healthIndex = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<HealthIndex200>(
      {url: `/api/health`, method: 'GET', signal
    },
      );
    }
  

export const getHealthIndexQueryKey = () => {
    return [`/api/health`] as const;
    }

    
export const getHealthIndexQueryOptions = <TData = Awaited<ReturnType<typeof healthIndex>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthIndex>>> = ({ signal }) => healthIndex(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthIndexQueryResult = NonNullable<Awaited<ReturnType<typeof healthIndex>>>
export type HealthIndexQueryError = unknown


export function useHealthIndex<TData = Awaited<ReturnType<typeof healthIndex>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthIndex>>,
          TError,
          Awaited<ReturnType<typeof healthIndex>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthIndex<TData = Awaited<ReturnType<typeof healthIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthIndex>>,
          TError,
          Awaited<ReturnType<typeof healthIndex>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthIndex<TData = Awaited<ReturnType<typeof healthIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthIndex<TData = Awaited<ReturnType<typeof healthIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthIndex>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthIndexQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



