/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Laravel
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  BillingCheckoutSession200,
  BillingCheckoutSession503,
  BillingPortalSession200,
  BillingPortalSession503,
  BillingStatus200
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const billingCheckoutSession = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<BillingCheckoutSession200>(
      {url: `/api/billing/checkout-session`, method: 'POST', signal
    },
      );
    }
  


export const getBillingCheckoutSessionMutationOptions = <TError = AuthenticationExceptionResponse | BillingCheckoutSession503,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingCheckoutSession>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingCheckoutSession>>, TError,void, TContext> => {

const mutationKey = ['billingCheckoutSession'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingCheckoutSession>>, void> = () => {
          

          return  billingCheckoutSession()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingCheckoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof billingCheckoutSession>>>
    
    export type BillingCheckoutSessionMutationError = AuthenticationExceptionResponse | BillingCheckoutSession503

    export const useBillingCheckoutSession = <TError = AuthenticationExceptionResponse | BillingCheckoutSession503,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingCheckoutSession>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingCheckoutSession>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getBillingCheckoutSessionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const billingPortalSession = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<BillingPortalSession200>(
      {url: `/api/billing/portal-session`, method: 'POST', signal
    },
      );
    }
  


export const getBillingPortalSessionMutationOptions = <TError = AuthenticationExceptionResponse | BillingPortalSession503,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingPortalSession>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingPortalSession>>, TError,void, TContext> => {

const mutationKey = ['billingPortalSession'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingPortalSession>>, void> = () => {
          

          return  billingPortalSession()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingPortalSessionMutationResult = NonNullable<Awaited<ReturnType<typeof billingPortalSession>>>
    
    export type BillingPortalSessionMutationError = AuthenticationExceptionResponse | BillingPortalSession503

    export const useBillingPortalSession = <TError = AuthenticationExceptionResponse | BillingPortalSession503,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingPortalSession>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingPortalSession>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getBillingPortalSessionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const billingStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<BillingStatus200>(
      {url: `/api/billing/status`, method: 'GET', signal
    },
      );
    }
  

export const getBillingStatusQueryKey = () => {
    return [`/api/billing/status`] as const;
    }

    
export const getBillingStatusQueryOptions = <TData = Awaited<ReturnType<typeof billingStatus>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof billingStatus>>> = ({ signal }) => billingStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BillingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof billingStatus>>>
export type BillingStatusQueryError = AuthenticationExceptionResponse


export function useBillingStatus<TData = Awaited<ReturnType<typeof billingStatus>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingStatus>>,
          TError,
          Awaited<ReturnType<typeof billingStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingStatus<TData = Awaited<ReturnType<typeof billingStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingStatus>>,
          TError,
          Awaited<ReturnType<typeof billingStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingStatus<TData = Awaited<ReturnType<typeof billingStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBillingStatus<TData = Awaited<ReturnType<typeof billingStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBillingStatusQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



