/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Laravel
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  LinkedInAuth0200,
  LinkedInAuth0422,
  LinkedInCallback0200,
  LinkedInCallback0400,
  LinkedInDisconnect200,
  LinkedInStatus200
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const linkedInAuth0 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LinkedInAuth0200>(
      {url: `/api/auth/linkedin/auth`, method: 'GET', signal
    },
      );
    }
  

export const getLinkedInAuth0QueryKey = () => {
    return [`/api/auth/linkedin/auth`] as const;
    }

    
export const getLinkedInAuth0QueryOptions = <TData = Awaited<ReturnType<typeof linkedInAuth0>>, TError = AuthenticationExceptionResponse | LinkedInAuth0422>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLinkedInAuth0QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof linkedInAuth0>>> = ({ signal }) => linkedInAuth0(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LinkedInAuth0QueryResult = NonNullable<Awaited<ReturnType<typeof linkedInAuth0>>>
export type LinkedInAuth0QueryError = AuthenticationExceptionResponse | LinkedInAuth0422


export function useLinkedInAuth0<TData = Awaited<ReturnType<typeof linkedInAuth0>>, TError = AuthenticationExceptionResponse | LinkedInAuth0422>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInAuth0>>,
          TError,
          Awaited<ReturnType<typeof linkedInAuth0>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInAuth0<TData = Awaited<ReturnType<typeof linkedInAuth0>>, TError = AuthenticationExceptionResponse | LinkedInAuth0422>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInAuth0>>,
          TError,
          Awaited<ReturnType<typeof linkedInAuth0>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInAuth0<TData = Awaited<ReturnType<typeof linkedInAuth0>>, TError = AuthenticationExceptionResponse | LinkedInAuth0422>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLinkedInAuth0<TData = Awaited<ReturnType<typeof linkedInAuth0>>, TError = AuthenticationExceptionResponse | LinkedInAuth0422>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInAuth0>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLinkedInAuth0QueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const linkedInCallback0 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LinkedInCallback0200>(
      {url: `/api/auth/linkedin/callback`, method: 'GET', signal
    },
      );
    }
  

export const getLinkedInCallback0QueryKey = () => {
    return [`/api/auth/linkedin/callback`] as const;
    }

    
export const getLinkedInCallback0QueryOptions = <TData = Awaited<ReturnType<typeof linkedInCallback0>>, TError = LinkedInCallback0400>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLinkedInCallback0QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof linkedInCallback0>>> = ({ signal }) => linkedInCallback0(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LinkedInCallback0QueryResult = NonNullable<Awaited<ReturnType<typeof linkedInCallback0>>>
export type LinkedInCallback0QueryError = LinkedInCallback0400


export function useLinkedInCallback0<TData = Awaited<ReturnType<typeof linkedInCallback0>>, TError = LinkedInCallback0400>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInCallback0>>,
          TError,
          Awaited<ReturnType<typeof linkedInCallback0>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInCallback0<TData = Awaited<ReturnType<typeof linkedInCallback0>>, TError = LinkedInCallback0400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInCallback0>>,
          TError,
          Awaited<ReturnType<typeof linkedInCallback0>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInCallback0<TData = Awaited<ReturnType<typeof linkedInCallback0>>, TError = LinkedInCallback0400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLinkedInCallback0<TData = Awaited<ReturnType<typeof linkedInCallback0>>, TError = LinkedInCallback0400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInCallback0>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLinkedInCallback0QueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const linkedInStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LinkedInStatus200>(
      {url: `/api/linkedin/status`, method: 'GET', signal
    },
      );
    }
  

export const getLinkedInStatusQueryKey = () => {
    return [`/api/linkedin/status`] as const;
    }

    
export const getLinkedInStatusQueryOptions = <TData = Awaited<ReturnType<typeof linkedInStatus>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLinkedInStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof linkedInStatus>>> = ({ signal }) => linkedInStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LinkedInStatusQueryResult = NonNullable<Awaited<ReturnType<typeof linkedInStatus>>>
export type LinkedInStatusQueryError = AuthenticationExceptionResponse


export function useLinkedInStatus<TData = Awaited<ReturnType<typeof linkedInStatus>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInStatus>>,
          TError,
          Awaited<ReturnType<typeof linkedInStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInStatus<TData = Awaited<ReturnType<typeof linkedInStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof linkedInStatus>>,
          TError,
          Awaited<ReturnType<typeof linkedInStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLinkedInStatus<TData = Awaited<ReturnType<typeof linkedInStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLinkedInStatus<TData = Awaited<ReturnType<typeof linkedInStatus>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof linkedInStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLinkedInStatusQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const linkedInDisconnect = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LinkedInDisconnect200>(
      {url: `/api/linkedin/disconnect`, method: 'POST', signal
    },
      );
    }
  


export const getLinkedInDisconnectMutationOptions = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkedInDisconnect>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof linkedInDisconnect>>, TError,void, TContext> => {

const mutationKey = ['linkedInDisconnect'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkedInDisconnect>>, void> = () => {
          

          return  linkedInDisconnect()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkedInDisconnectMutationResult = NonNullable<Awaited<ReturnType<typeof linkedInDisconnect>>>
    
    export type LinkedInDisconnectMutationError = AuthenticationExceptionResponse

    export const useLinkedInDisconnect = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkedInDisconnect>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof linkedInDisconnect>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLinkedInDisconnectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    