/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Vox Prismatic
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthLogin200,
  AuthLoginBody,
  AuthLogout200,
  AuthMe200,
  AuthRegister200,
  AuthRegister409,
  AuthRegisterBody,
  AuthenticationExceptionResponse,
  ValidationExceptionResponse
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const authMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthMe200>(
      {url: `/api/auth/me`, method: 'GET', signal
    },
      );
    }
  

export const getAuthMeQueryKey = () => {
    return [`/api/auth/me`] as const;
    }

    
export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = AuthenticationExceptionResponse


export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const authLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogout200>(
      {url: `/api/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getAuthLogoutMutationOptions = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {
          

          return  authLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>
    
    export type AuthLogoutMutationError = AuthenticationExceptionResponse

    export const useAuthLogout = <TError = AuthenticationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authLogin = (
    authLoginBody: AuthLoginBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogin200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authLoginBody, signal
    },
      );
    }
  


export const getAuthLoginMutationOptions = <TError = ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBody}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: AuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = AuthLoginBody
    export type AuthLoginMutationError = ValidationExceptionResponse

    export const useAuthLogin = <TError = ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: AuthLoginBody},
        TContext
      > => {

      const mutationOptions = getAuthLoginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authRegister = (
    authRegisterBody: AuthRegisterBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthRegister200>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authRegisterBody, signal
    },
      );
    }
  


export const getAuthRegisterMutationOptions = <TError = AuthRegister409 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBody}, TContext> => {

const mutationKey = ['authRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegister>>, {data: AuthRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  authRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>
    export type AuthRegisterMutationBody = AuthRegisterBody
    export type AuthRegisterMutationError = AuthRegister409 | ValidationExceptionResponse

    export const useAuthRegister = <TError = AuthRegister409 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        {data: AuthRegisterBody},
        TContext
      > => {

      const mutationOptions = getAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    