/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Vox Prismatic
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminUpdateTrial200,
  AdminUpdateTrial404,
  AdminUpdateTrialBody,
  AdminUsage200,
  AdminUsageParams,
  AuthenticationExceptionResponse,
  ValidationExceptionResponse
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const adminUsage = (
    params?: AdminUsageParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminUsage200>(
      {url: `/api/admin/usage`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getAdminUsageQueryKey = (params?: AdminUsageParams,) => {
    return [`/api/admin/usage`, ...(params ? [params]: [])] as const;
    }

    
export const getAdminUsageQueryOptions = <TData = Awaited<ReturnType<typeof adminUsage>>, TError = AuthenticationExceptionResponse>(params?: AdminUsageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminUsageQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUsage>>> = ({ signal }) => adminUsage(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminUsageQueryResult = NonNullable<Awaited<ReturnType<typeof adminUsage>>>
export type AdminUsageQueryError = AuthenticationExceptionResponse


export function useAdminUsage<TData = Awaited<ReturnType<typeof adminUsage>>, TError = AuthenticationExceptionResponse>(
 params: undefined |  AdminUsageParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsage>>,
          TError,
          Awaited<ReturnType<typeof adminUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminUsage<TData = Awaited<ReturnType<typeof adminUsage>>, TError = AuthenticationExceptionResponse>(
 params?: AdminUsageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsage>>,
          TError,
          Awaited<ReturnType<typeof adminUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminUsage<TData = Awaited<ReturnType<typeof adminUsage>>, TError = AuthenticationExceptionResponse>(
 params?: AdminUsageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminUsage<TData = Awaited<ReturnType<typeof adminUsage>>, TError = AuthenticationExceptionResponse>(
 params?: AdminUsageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminUsageQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const adminUpdateTrial = (
    userId: string,
    adminUpdateTrialBody: AdminUpdateTrialBody,
 ) => {
      
      
      return customInstance<AdminUpdateTrial200>(
      {url: `/api/admin/users/${userId}/trial`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: adminUpdateTrialBody
    },
      );
    }
  


export const getAdminUpdateTrialMutationOptions = <TError = AuthenticationExceptionResponse | AdminUpdateTrial404 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateTrial>>, TError,{userId: string;data: AdminUpdateTrialBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateTrial>>, TError,{userId: string;data: AdminUpdateTrialBody}, TContext> => {

const mutationKey = ['adminUpdateTrial'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateTrial>>, {userId: string;data: AdminUpdateTrialBody}> = (props) => {
          const {userId,data} = props ?? {};

          return  adminUpdateTrial(userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateTrialMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateTrial>>>
    export type AdminUpdateTrialMutationBody = AdminUpdateTrialBody
    export type AdminUpdateTrialMutationError = AuthenticationExceptionResponse | AdminUpdateTrial404 | ValidationExceptionResponse

    export const useAdminUpdateTrial = <TError = AuthenticationExceptionResponse | AdminUpdateTrial404 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateTrial>>, TError,{userId: string;data: AdminUpdateTrialBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateTrial>>,
        TError,
        {userId: string;data: AdminUpdateTrialBody},
        TContext
      > => {

      const mutationOptions = getAdminUpdateTrialMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    