/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Vox Prismatic
 * Content Creation Platform API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  TranscriptsGet200,
  TranscriptsPreviewBody,
  TranscriptsPut200,
  TranscriptsPutBody,
  ValidationExceptionResponse
} from '../generated.schemas';

import { customInstance } from '../../lib/client/orval-fetcher';




export const transcriptsPreview = (
    transcriptsPreviewBody: TranscriptsPreviewBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/transcripts/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transcriptsPreviewBody, signal
    },
      );
    }
  


export const getTranscriptsPreviewMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transcriptsPreview>>, TError,{data: TranscriptsPreviewBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof transcriptsPreview>>, TError,{data: TranscriptsPreviewBody}, TContext> => {

const mutationKey = ['transcriptsPreview'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transcriptsPreview>>, {data: TranscriptsPreviewBody}> = (props) => {
          const {data} = props ?? {};

          return  transcriptsPreview(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranscriptsPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof transcriptsPreview>>>
    export type TranscriptsPreviewMutationBody = TranscriptsPreviewBody
    export type TranscriptsPreviewMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useTranscriptsPreview = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transcriptsPreview>>, TError,{data: TranscriptsPreviewBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof transcriptsPreview>>,
        TError,
        {data: TranscriptsPreviewBody},
        TContext
      > => {

      const mutationOptions = getTranscriptsPreviewMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const transcriptsGet = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TranscriptsGet200>(
      {url: `/api/transcripts/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getTranscriptsGetQueryKey = (id?: string,) => {
    return [`/api/transcripts/${id}`] as const;
    }

    
export const getTranscriptsGetQueryOptions = <TData = Awaited<ReturnType<typeof transcriptsGet>>, TError = AuthenticationExceptionResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTranscriptsGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof transcriptsGet>>> = ({ signal }) => transcriptsGet(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TranscriptsGetQueryResult = NonNullable<Awaited<ReturnType<typeof transcriptsGet>>>
export type TranscriptsGetQueryError = AuthenticationExceptionResponse


export function useTranscriptsGet<TData = Awaited<ReturnType<typeof transcriptsGet>>, TError = AuthenticationExceptionResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transcriptsGet>>,
          TError,
          Awaited<ReturnType<typeof transcriptsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranscriptsGet<TData = Awaited<ReturnType<typeof transcriptsGet>>, TError = AuthenticationExceptionResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transcriptsGet>>,
          TError,
          Awaited<ReturnType<typeof transcriptsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranscriptsGet<TData = Awaited<ReturnType<typeof transcriptsGet>>, TError = AuthenticationExceptionResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTranscriptsGet<TData = Awaited<ReturnType<typeof transcriptsGet>>, TError = AuthenticationExceptionResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof transcriptsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTranscriptsGetQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const transcriptsPut = (
    id: string,
    transcriptsPutBody: TranscriptsPutBody,
 ) => {
      
      
      return customInstance<TranscriptsPut200>(
      {url: `/api/transcripts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: transcriptsPutBody
    },
      );
    }
  


export const getTranscriptsPutMutationOptions = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transcriptsPut>>, TError,{id: string;data: TranscriptsPutBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof transcriptsPut>>, TError,{id: string;data: TranscriptsPutBody}, TContext> => {

const mutationKey = ['transcriptsPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transcriptsPut>>, {id: string;data: TranscriptsPutBody}> = (props) => {
          const {id,data} = props ?? {};

          return  transcriptsPut(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranscriptsPutMutationResult = NonNullable<Awaited<ReturnType<typeof transcriptsPut>>>
    export type TranscriptsPutMutationBody = TranscriptsPutBody
    export type TranscriptsPutMutationError = AuthenticationExceptionResponse | ValidationExceptionResponse

    export const useTranscriptsPut = <TError = AuthenticationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transcriptsPut>>, TError,{id: string;data: TranscriptsPutBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof transcriptsPut>>,
        TError,
        {id: string;data: TranscriptsPutBody},
        TContext
      > => {

      const mutationOptions = getTranscriptsPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    